name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: ["oldstable", "stable"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: |
          sudo apt update
          sudo apt install -y ldap-utils
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test \
          -v \
          -shuffle=on \
          -coverprofile=coverage.txt \
          -covermode=atomic \
          -coverpkg=../... \
          ./...
      - uses: codecov/codecov-action@v6
        with:
          use_oidc: true
